// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlOzvMOYHWP8ivHKhIdvwJVQpJSN8QAZI',
    appId: '1:965410684856:web:8455ca3fedcb6c6106594d',
    messagingSenderId: '965410684856',
    projectId: 'mpolo-d0cfb',
    authDomain: 'mpolo-d0cfb.firebaseapp.com',
    storageBucket: 'mpolo-d0cfb.firebasestorage.app',
    measurementId: 'G-0XGPG2PGY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp0g39U-GVXIXhHWqZzSlqGgpUVj56KF8',
    appId: '1:965410684856:android:a6106824647ea22006594d',
    messagingSenderId: '965410684856',
    projectId: 'mpolo-d0cfb',
    storageBucket: 'mpolo-d0cfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkMZmeVdPvN9LJO2Xlt_GDvbMDiMOWWfQ',
    appId: '1:965410684856:ios:b9ebba32b452220f06594d',
    messagingSenderId: '965410684856',
    projectId: 'mpolo-d0cfb',
    storageBucket: 'mpolo-d0cfb.firebasestorage.app',
    iosBundleId: 'com.example.samrath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkMZmeVdPvN9LJO2Xlt_GDvbMDiMOWWfQ',
    appId: '1:965410684856:ios:b9ebba32b452220f06594d',
    messagingSenderId: '965410684856',
    projectId: 'mpolo-d0cfb',
    storageBucket: 'mpolo-d0cfb.firebasestorage.app',
    iosBundleId: 'com.example.samrath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlOzvMOYHWP8ivHKhIdvwJVQpJSN8QAZI',
    appId: '1:965410684856:web:aa86e51d7a4046e206594d',
    messagingSenderId: '965410684856',
    projectId: 'mpolo-d0cfb',
    authDomain: 'mpolo-d0cfb.firebaseapp.com',
    storageBucket: 'mpolo-d0cfb.firebasestorage.app',
    measurementId: 'G-F6EX3EMG45',
  );
}
